name: Expression and Context
on: [workflow_dispatch]
env:
  continue: true
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github contexts
        run: echo "${{toJson(github)}}"

      - name: Print Repo Owner
        run: echo "${{ github.repository_owner }}"

      - name: failed job
        
        continue-on-error: ${{ fromJSON(env.continue) }}
        run: exit 1

      - name: Post failed job
        run: echo "Running even on previous step fail"